default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: chat_development
  username: nayt
  password: 
  host: localhost
  port: 5432

test:
  <<: *default
  database: chat_test


# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  database: chat_production
  username: nayt
  password: <%= ENV['CHAT_DATABASE_PASSWORD'] %>
